### ISSUE TITLE
animated gifs on another major modes?

### ISSUE THREAD

**Issue by camelo003** [shg/org-inline-anim.el#3]
great work in this one! congratulations and thanks for sharing =] !

im not an elist specialist, but it would be possible to this function work on other major modes? im using this function to draw images directly in eshell:

```elisp
(defun eshell/imgcat (&rest args)
  "Display image files."
  (unless args (error "Usage: imgcat FILE ..."))
  (dolist (img (eshell-flatten-list args))
    (eshell-printn
     (propertize " " 'display (create-image img)))))

```

**Comment by shg** [comment]
Thank you very much for your positive comment about org-inline-anim.el.

I don't know the specific way to do this in eshell because I haven't seen the eshell code, but if you can display images in eshell, you can probably animate gif animations in the same way as org-inline-anim.el does.

What org-inline-anim.el does is simple: it gets the overlay of the displayed image and plays it back with `image-animate`.

**Comment by camelo003** [comment]
Thank you very much for the answer =] ! The time has come to get my hands dirty with elisp (and a bit of research, haha).

I wrote here in the issues because I couldn't find another channel. But you can mark it as resolved, of course. If there is any news about it, I will update it here. Thanks again!

**Comment by shg** [comment]
Good luck!
